export type { Platform, PlatformId } from './platform'
export { PlatformProvider, usePlatform } from './platform-provider'
export { InMemoryPlatform, type InMemoryPlatformOptions } from './in-memory-platform'
export { SEED_NOTES } from './in-memory-seed'
export { WebPlatform, type NotesApiClient } from './web-platform'
